# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.assets.gulp_rev_version_strategy:
        class: AppBundle\Twig\GulpRevVersionStrategy
        arguments: ["%kernel.root_dir%/Resources/assets"]
        public: false
